-- MySQL Script generated by MySQL Workbench
-- Thu 07 Nov 2019 09:11:44 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scheduleDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `scheduleDatabase` ;

-- -----------------------------------------------------
-- Schema scheduleDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scheduleDatabase` DEFAULT CHARACTER SET utf8 ;
USE `scheduleDatabase` ;

-- -----------------------------------------------------
-- Table `scheduleDatabase`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scheduleDatabase`.`user` ;

CREATE TABLE IF NOT EXISTS `scheduleDatabase`.`user` (
  `user_Id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `hashed_password` MEDIUMTEXT NULL,
  `email` VARCHAR(100) NULL,
  `is_admin` TINYINT(1) NULL,
  PRIMARY KEY (`user_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scheduleDatabase`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scheduleDatabase`.`course` ;

CREATE TABLE IF NOT EXISTS `scheduleDatabase`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `last_update` DATE NULL,
  `created_by` INT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_course_user_idx` (`created_by` ASC),
  CONSTRAINT `fk_course_user`
    FOREIGN KEY (`created_by`)
    REFERENCES `scheduleDatabase`.`user` (`user_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scheduleDatabase`.`classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scheduleDatabase`.`classroom` ;

CREATE TABLE IF NOT EXISTS `scheduleDatabase`.`classroom` (
  `classroom_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `floor` INT(11) NULL,
  PRIMARY KEY (`classroom_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scheduleDatabase`.`lecture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scheduleDatabase`.`lecture` ;

CREATE TABLE IF NOT EXISTS `scheduleDatabase`.`lecture` (
  `lecture_id` INT NOT NULL AUTO_INCREMENT,
  `prof_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `course_course_id` INT NOT NULL,
  PRIMARY KEY (`lecture_id`),
  INDEX `fk_lecture_classroom1_idx` (`room_id` ASC),
  INDEX `fk_lecture_course1_idx` (`course_course_id` ASC),
  INDEX `fk_lecture_user1_idx` (`prof_id` ASC),
  CONSTRAINT `fk_lecture_classroom1`
    FOREIGN KEY (`room_id`)
    REFERENCES `scheduleDatabase`.`classroom` (`classroom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecture_course1`
    FOREIGN KEY (`course_course_id`)
    REFERENCES `scheduleDatabase`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecture_user1`
    FOREIGN KEY (`prof_id`)
    REFERENCES `scheduleDatabase`.`user` (`user_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scheduleDatabase`.`slotevent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scheduleDatabase`.`slotevent` ;

CREATE TABLE IF NOT EXISTS `scheduleDatabase`.`slotevent` (
  `slot_event_id` INT NOT NULL AUTO_INCREMENT,
  `day` VARCHAR(45) NULL,
  `hour` VARCHAR(45) NULL,
  PRIMARY KEY (`slot_event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scheduleDatabase`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scheduleDatabase`.`schedule` ;

CREATE TABLE IF NOT EXISTS `scheduleDatabase`.`schedule` (
  `lecture_id` INT NOT NULL,
  `slot_event_id` INT NOT NULL,
  PRIMARY KEY (`lecture_id`, `slot_event_id`),
  INDEX `fk_lecture_has_slotEvent_slotEvent1_idx` (`slot_event_id` ASC),
  INDEX `fk_lecture_has_slotEvent_lecture1_idx` (`lecture_id` ASC),
  CONSTRAINT `fk_lecture_has_slotEvent_lecture1`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `scheduleDatabase`.`lecture` (`lecture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecture_has_slotEvent_slotEvent1`
    FOREIGN KEY (`slot_event_id`)
    REFERENCES `scheduleDatabase`.`slotevent` (`slot_event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
