-- MySQL Script generated by MySQL Workbench
-- Sun 13 Oct 2019 10:43:45 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- create by Iando Rafidimalala

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema course
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS AMT_COURSE;
CREATE SCHEMA IF NOT EXISTS AMT_COURSE DEFAULT CHARACTER SET utf8 ;
USE AMT_COURSE ;

-- -----------------------------------------------------
-- Table structure for table `user`
-- -----------------------------------------------------
CREATE TABLE users (
  `userId` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) ,
  `lastName` VARCHAR(45) ,
  `userName` VARCHAR(45) ,
  `email` VARCHAR(45) ,
  `userPassword` VARCHAR(45) NOT NULL,
  `telephone` INT(11) NULL,
  `wallet` FLOAT NULL,  
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PRIMARY KEY (`userId`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE users ENGINE=InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table structure for table `course`
-- -----------------------------------------------------
CREATE TABLE courses (
  `courseId` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `createdBy` INT NOT NULL,	  
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PRIMARY KEY (`courseId`)
);
ALTER TABLE courses ENGINE=InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

ALTER TABLE courses ADD CONSTRAINT FOREIGN KEY (createdBy) REFERENCES user (userId) ON DELETE RESTRICT ON UPDATE CASCADE;

SET CHARSET 'utf8';


--
-- Dumping data for tables
--

INSERT INTO users (firstName, lastName, userName, email, userPassword, telephone, wallet)
VALUES ("Nuno", "Abrantes", "nuno", "nuno.abrantes@heig-vd.ch","123456789","0780811111", 100),
       ("Peta", "Auschnok", "peta", "pa@schnok.com","123456789","0780822222", 200),
       ("Do", "Re", "do", "mi.fa@sol.la", "123456789", "0780833333", 101),
       ("Apme", "Bezara", "apme", "appme.bezara@tier.org", "123456789", "0780844444", 210);

INSERT INTO courses (title, description, createdBy)
VALUES ("STI", "Sécurité Internet", 1),
       ("AMT", "Application Multi-Tiers", 2),
       ("RES", "Réseau", 3),
       ("GRX", "Gestion des réseaux", 4),
       ("TTR", "Télétrafic", 1),
       ("AIT", "Administration IT", 2),
       ("POO", "Progrmmation orienté objet", 3),
       ("SAN", "Storage Area Network", 1);
