version: '3'
services:
  payara:
    build: ../images/payara
    container_name: payaraserv
    links:
      - mysql:db
    ports:
      - "8080:8080"
      - "4848:4848"
    volumes:
      - ../Project-HEIGVD-AMT-2019-CourseApp/target:/opt/payara/deployments/     
  mysql:
    build: ../images/mysql
    container_name: mysqlcourse
    environment:
      - MYSQL_DATABASE=AMT_SCHEDULE
      - MYSQL_USER=root
      - MYSQL_PASS=adminpw
      - MYSQL_ROOT_PASSWORD=adminpw      
    ports:
      - "3306:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    container_name: phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "6060:80"
    links:
      - mysql:db
