version: '3'
services:
  payara:
    build: ../images/payara
    links:
      - mysql:db
    ports:
      - "8080:8080"
      - "4848:4848"
    volumes:
      - ../Project-HEIGVD-AMT-2019-CourseManagerApp/target:/opt/payara/deployments/      
  wildfly:
    build: ../images/wildfly
    ports:
      - "9090:8080"
      - "9990:9990"
    links:
      - mysql:db
  mysql:
    build: ../images/mysql
    environment:
      - MYSQL_DATABASE=AMT_COURSE
      - MYSQL_USER=root
      - MYSQL_PASS=adminpw
      - MYSQL_ROOT_PASSWORD=adminpw      
    ports:
      - "3306:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    container_name: phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "6060:80"
    links:
      - mysql:db
